# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ElectronicsGeek
tagline:          'The New Blog...'
description:      'The musings of an enthusiastic spare-time programmer, maker and electronics enthusiast.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Gregory Parker'
  profile-pic:    https://avatars2.githubusercontent.com/u/9054912?
  url:            https://twitter.com/EGeek_Online

paginate:         5

github:
  repo:           https://github.com/ElectronicsGeek/electronicsgeek.github.io
